### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './dataset/train.pkl'

### ISSUE THREAD

**Issue by yanghhx** [yongqyu/st-gcn-pytorch#14]
when I run "python main.py" error like this :Traceback (most recent call last):
  File "main.py", line 14, in <module>
    train_tensor, train_label = torch.load(args.train_path)
  File "/home/yang/anaconda3/envs/yolov3/lib/python3.7/site-packages/torch/serialization.py", line 365, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './dataset/train.pkl'
so where should I put the data.set "Florence_3d_actions"?

**Comment by xumingna** [comment]
Hello, I also encountered this problem. Have you solved it

**Comment by Zxl1556180489** [comment]
Hello, I also encountered this problem. Have you solved it

**Comment by Zxl1556180489** [comment]
> Hello, I also encountered this problem. Have you solved it

https://github.com/yongqyu/st-gcn-pytorch/issues/8#issuecomment-806444697

**Comment by Zxl1556180489** [comment]
> Hello, I also encountered this problem. Have you solved it

Have you solved it

**Comment by yanghhx** [comment]
Sorry , I failed it.







在 2021-08-13 17:16:55，"Zxl1556180489" ***@***.***> 写道：

Hello, I also encountered this problem. Have you solved it

#8 (comment)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zxl1556180489** [comment]
> Sorry , I failed it. 在 2021-08-13 17:16:55，"Zxl1556180489" ***@***.***> 写道： Hello, I also encountered this problem. Have you solved it #8 (comment) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

first，run preprocess.py
