### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './models/model-2.pkl'

### ISSUE THREAD

**Issue by xibian1120** [yongqyu/st-gcn-pytorch#19]
```python
Traceback (most recent call last):
  File "main.py", line 132, in <module>
    train()
  File "main.py", line 105, in train
    torch.save(model.state_dict(), os.path.join(args.model_path, 'model-%d.pkl'%(best_epoch)))
  File "/media/yxl/a/2025191008/env/gcn1/lib/python3.6/site-packages/torch-1.10.2-py3.6-linux-x86_64.egg/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/media/yxl/a/2025191008/env/gcn1/lib/python3.6/site-packages/torch-1.10.2-py3.6-linux-x86_64.egg/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/media/yxl/a/2025191008/env/gcn1/lib/python3.6/site-packages/torch-1.10.2-py3.6-linux-x86_64.egg/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './models/model-2.pkl'
```

**Comment by Mint0621** [comment]
Need to create an empty folder：”./models"
