### ISSUE TITLE
add a point of data 

### ISSUE THREAD

**Issue by tiredDi** [yongqyu/st-gcn-pytorch#2]
Sorry to border you again, I have another question about  Florence_dataset_WorldCoordinates.txt.
The original txt file has 15 points of data, I would like to add a point. I copied the 3D data of one point to he 16th point, but it report an error, I have no idea, can u help me?
Looking for your reply. Thanks

The number of parameters: 69527
Traceback (most recent call last):
  File "/home/wtu/project/action-recognition_GCN/st-gcn-pytorch_fabric/main.py", line 133, in <module>
    train()
  File "/home/wtu/project/action-recognition_GCN/st-gcn-pytorch_fabric/main.py", line 76, in train
    logit = model(x[0].float())
  File "/home/wtu/anaconda3/envs/py/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wtu/project/action-recognition_GCN/st-gcn-pytorch_fabric/model.py", line 36, in forward
    x = torch.cat((x, node_features.permute(0,2,1).unsqueeze(1).repeat(1,32,1,1)), 3)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 3. Got 15 and 16 in dimension 2 at /opt/conda/conda-bld/pytorch_1556653109872/work/aten/src/THC/generic/THCTensorMath.cu:71

**Comment by yongqyu** [comment]
I do not know if you've solved this problem.
In the line where the error occurs, check the size of ```x``` and ```node_feature```.
It seems that the size does not match as a point is added.
